# Generated by Django 3.2.7 on 2021-09-25 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_api', '0003_alter_tag_color'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portions',
            new_name='Portion',
        ),
    ]
