# Generated by Django 3.2.7 on 2021-10-16 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_api', '0009_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['id']},
        ),
    ]
