# Generated by Django 3.2.7 on 2021-10-16 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_api', '0010_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={},
        ),
    ]
