# Generated by Django 3.2.7 on 2021-10-23 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_api', '0011_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['user'], 'verbose_name': "Indicator of a User's favorite Recipe", 'verbose_name_plural': "Indicators of Users' favorite Recipes"},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name'], 'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='portion',
            options={'ordering': ['recipe'], 'verbose_name': 'Amount of an Ingredient in a Recipe', 'verbose_name_plural': 'Amounts of Ingredients in Recipes'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['name'], 'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ['user'], 'verbose_name': 'Indicator of a Recipe in a Shopping Cart', 'verbose_name_plural': 'Indicators of Recipes in Shopping Carts'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
