# Generated by Django 3.2.7 on 2021-10-23 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_api', '0012_auto_20211023_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['user'], 'verbose_name': "User's favorite Recipe", 'verbose_name_plural': "Users' favorite Recipes"},
        ),
        migrations.AlterModelOptions(
            name='portion',
            options={'ordering': ['recipe'], 'verbose_name': 'Ingredient in a Recipe', 'verbose_name_plural': 'Ingredients in Recipes'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ['user'], 'verbose_name': 'Recipe in Shopping Cart', 'verbose_name_plural': 'Recipes in Shopping Carts'},
        ),
    ]
