# Generated by Django 3.2.7 on 2021-10-23 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_api', '0013_auto_20211023_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(
                1, message='Minimum cooking time is 1 minute.')]),
        ),
    ]
