# Generated by Django 3.2.7 on 2021-10-24 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_api', '0016_alter_portion_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portion',
            unique_together=set(),
        ),
    ]
