# Generated by Django 3.2.7 on 2021-10-24 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_api', '0017_alter_portion_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portion',
            unique_together={('recipe', 'ingredient')},
        ),
    ]
