# Generated by Django 3.2.7 on 2021-10-24 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_api', '0017_auto_20211024_2157'),
        ('foodgram_api', '0018_alter_portion_unique_together'),
    ]

    operations = [
    ]
